import { useState, useEffect, memo } from 'react';
import { Wordmark } from '../Wordmark';
import { colors } from '../../styles/designSystem';

interface TermsScreenProps {
  onBack: () => void;
}

const BackIcon = memo(function BackIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M19 12H5M12 19l-7-7 7-7" />
    </svg>
  );
});

export function TermsScreen({ onBack }: TermsScreenProps) {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setIsVisible(true), 150);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div
      className="relative"
      style={{
        background: 'var(--color-void)',
        minHeight: '100dvh',
        color: 'rgba(255,248,240,0.95)',
      }}
      role="main"
      aria-labelledby="terms-heading"
    >
      {/* AImighty logo — fixed top-center. top-6 (24px) gives a touch
          more breathing room above the wordmark on notched devices than
          the old top-5. */}
      <div
        className="fixed top-6 left-1/2 z-20"
        style={{ transform: 'translateX(-50%)' }}
      >
        <Wordmark size="sm" style={{ fontSize: '1.1rem' }} />
      </div>
      {/* Back button */}
      <nav
        className="fixed top-4 left-4 z-20"
        style={{
          opacity: isVisible ? 1 : 0,
          transition: 'opacity 0.5s ease',
        }}
      >
        <button
          onClick={onBack}
          aria-label="Go back"
          className="flex items-center gap-2 py-2 px-3 rounded-lg transition-colors hover:bg-white/5"
          style={{ color: 'rgba(255, 255, 255, 0.5)' }}
        >
          <BackIcon />
          <span style={{ fontSize: 'var(--text-sm)' }}>Back</span>
        </button>
      </nav>

      {/* Content */}
      <div className="relative z-10 overflow-y-auto" style={{ minHeight: '100dvh' }}>
        <div
          className="max-w-[800px] mx-auto px-6 pt-28 pb-20"
          style={{
            opacity: isVisible ? 1 : 0,
            transform: isVisible ? 'translateY(0)' : 'translateY(30px)',
            transition: 'all 0.6s ease',
          }}
        >
          <h1
            id="terms-heading"
            className="mb-4"
            style={{
              fontFamily: 'var(--font-display)',
              fontSize: 'var(--text-3xl)',
              fontWeight: 300,
              color: colors.gold,
            }}
          >
            Terms of Service
          </h1>

          <p
            className="mb-2"
            style={{
              fontSize: 'var(--text-sm)',
              color: 'rgba(255, 255, 255, 0.35)',
            }}
          >
            Last Updated: April 14, 2026
          </p>
          <p
            className="mb-8"
            style={{
              fontSize: 'var(--text-sm)',
              color: 'rgba(255, 255, 255, 0.35)',
            }}
          >
            Effective Date: April 14, 2026
          </p>

          <div
            className="space-y-6"
            style={{
              fontFamily: 'var(--font-body)',
              fontSize: 'var(--text-base)',
              fontWeight: 400,
              color: 'rgba(255, 255, 255, 0.7)',
              lineHeight: 1.8,
            }}
          >
            <p>
              Welcome to AImighty ("we," "us," "our," or the "Company"), operated by Robby Hess, doing business as AImighty. These Terms of Service ("Terms") govern your access to and use of the AImighty website at aimightyme.com, the AImighty progressive web application, and all related services (collectively, the "Service").
            </p>
            <p>
              By creating an account, accessing, or using the Service, you agree to be bound by these Terms. If you do not agree to these Terms, do not use the Service.
            </p>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 1 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                1. NATURE OF THE SERVICE — IMPORTANT DISCLAIMER
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                1.1 AI-Generated Content
              </h3>
              <p>
                AImighty is an artificial intelligence application that generates text and audio responses using large language models and text-to-speech technology. <strong style={{ color: 'rgba(255, 255, 255, 0.95)' }}>All responses provided by AImighty are generated by artificial intelligence. You are not communicating with God, a deity, a divine being, a religious figure, or any supernatural entity.</strong> You are interacting with an AI system that generates responses based on patterns learned from sacred texts, religious scholarship, philosophical works, and other publicly available materials.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                1.2 Not a Religious Authority
              </h3>
              <p>
                AImighty is not a church, religious organization, denomination, ministry, or religious authority of any kind. We are a technology company providing an AI-powered tool for spiritual reflection and exploration. AImighty is not endorsed by, affiliated with, or sponsored by any religious organization, denomination, clergy body, or spiritual leader.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                1.3 Not a Substitute for Professional Services
              </h3>
              <p>
                The Service is intended for personal reflection, spiritual exploration, and educational purposes only. AImighty is <strong style={{ color: 'rgba(255, 255, 255, 0.95)' }}>NOT</strong> a substitute for:
              </p>
              <ul className="list-disc list-inside space-y-2 mt-4 ml-4">
                <li>Licensed therapy, counseling, or mental health treatment</li>
                <li>Medical advice, diagnosis, or treatment</li>
                <li>Legal advice or representation</li>
                <li>Financial advice or planning</li>
                <li>Pastoral care, clergy counseling, or religious community</li>
                <li>Suicide prevention or crisis intervention services</li>
              </ul>
              <div
                className="p-4 rounded-xl mt-4"
                style={{
                  background: 'rgba(239, 68, 68, 0.1)',
                  border: '1px solid rgba(239, 68, 68, 0.3)',
                }}
              >
                <p style={{ color: 'rgba(255, 255, 255, 0.95)' }}>
                  <strong>If you are experiencing a medical emergency, call 911 (or your local emergency number). If you are experiencing suicidal thoughts or a mental health crisis, contact the 988 Suicide & Crisis Lifeline by calling or texting 988.</strong>
                </p>
              </div>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                1.4 No Guarantee of Accuracy
              </h3>
              <p>
                AI-generated responses may contain inaccuracies, misquotations, fabricated scripture references, doctrinal errors, or information that contradicts the actual teachings of any religious tradition. We make no warranty that any scripture citation, theological claim, or spiritual guidance provided by the Service is accurate, complete, or doctrinally sound. <strong style={{ color: 'rgba(255, 255, 255, 0.95)' }}>You should independently verify any scripture references, religious teachings, or factual claims provided by the Service before relying upon them.</strong>
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                1.5 Assumption of Risk
              </h3>
              <p>
                You acknowledge and agree that any decisions you make based on content generated by the Service are made at your own risk. You agree not to rely on the Service as your sole source of spiritual guidance, religious instruction, or life advice. We strongly encourage you to consult with qualified clergy, religious leaders, therapists, counselors, or other licensed professionals for guidance on significant life decisions.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 2 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                2. ELIGIBILITY
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                2.1 Age Requirement
              </h3>
              <p>
                You must be at least 13 years of age to create an account and use the Service. If you are between 13 and 18 years of age (or the age of legal majority in your jurisdiction), you may only use the Service with the consent and supervision of a parent or legal guardian who agrees to be bound by these Terms on your behalf.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                2.2 Parental Responsibility
              </h3>
              <p>
                If you are a parent or legal guardian who has consented to a minor's use of the Service, you are fully responsible for that minor's use of the Service, including all financial charges and legal liability.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                2.3 Jurisdictional Compliance
              </h3>
              <p>
                You are responsible for ensuring that your use of the Service complies with all applicable laws in your jurisdiction. Some jurisdictions may restrict or prohibit the use of AI systems that simulate religious or spiritual entities. It is your responsibility to determine whether your use of the Service is lawful in your location.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 3 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                3. ACCOUNTS AND REGISTRATION
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                3.1 Account Creation
              </h3>
              <p>
                To use the Service, you must create an account by providing a valid email address and creating a password. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                3.2 Account Security
              </h3>
              <p>
                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately at support@aimightyme.com of any unauthorized use of your account or any other breach of security.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                3.3 One Account Per Person
              </h3>
              <p>
                Each individual may maintain only one account. Creating multiple accounts to circumvent usage limits, abuse free trials, or for any other purpose is prohibited and may result in termination of all associated accounts.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 4 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                4. SUBSCRIPTION PLANS AND BILLING
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                4.1 Free Trial
              </h3>
              <p>
                New users receive a limited free trial consisting of 3 messages. After the free trial, continued use of the Service requires a paid subscription.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                4.2 Subscription Tiers
              </h3>
              <p>We offer the following subscription tiers, which may be modified from time to time:</p>
              <ul className="list-disc list-inside space-y-2 mt-4 ml-4">
                <li><strong>Believer ($4.99/month or $47.00/year):</strong> 10 conversations per day, text responses with browser-based voice output, all 14 belief systems, Midjourney-generated image backgrounds, daily prayer, sacred text, and Daily Belief Study.</li>
                <li><strong>Divine ($14.99/month or $119.00/year):</strong> 20 conversations per day, premium AI voice output, character voice selection (God, Jesus, Mary, and belief-specific equivalents), conversation history and memory, personal library of saved reflections, all Believer features.</li>
              </ul>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                4.3 Billing and Renewal
              </h3>
              <p>
                Subscriptions are billed in advance on a monthly or annual basis depending on the plan you select. Your subscription will automatically renew at the end of each billing period unless you cancel before the renewal date. You authorize us to charge your payment method on file for the applicable subscription fee at each renewal.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                4.4 Cancellation
              </h3>
              <p>
                You may cancel your subscription at any time through your account settings or by contacting us at support@aimightyme.com. Cancellation takes effect at the end of your current billing period. No refunds will be issued for partial billing periods. After cancellation, you will retain access to your subscription features until the end of your current billing period.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                4.5 Free Trial Period
              </h3>
              <p>
                If you sign up for a free trial period that requires a payment method on file, you will be charged the applicable subscription fee at the end of the trial period unless you cancel before the trial expires. We will notify you before any charges are applied.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                4.6 Price Changes
              </h3>
              <p>
                We reserve the right to change subscription prices at any time. Any price changes will be communicated to you at least 30 days in advance and will take effect at the start of your next billing period. Your continued use of the Service after the price change constitutes your acceptance of the new pricing.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 5 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                5. ACCEPTABLE USE
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                5.1 Permitted Use
              </h3>
              <p>
                You may use the Service for personal spiritual reflection, religious exploration, educational purposes, and general conversation as intended by the Service design.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                5.2 Prohibited Conduct
              </h3>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-2 mt-4 ml-4">
                <li>Attempt to make the AI generate content that promotes violence, hatred, discrimination, or illegal activity</li>
                <li>Use the Service to harass, abuse, threaten, or intimidate any person or group</li>
                <li>Share, publish, or distribute AI-generated content in a manner that misleads others into believing it is actual divine communication</li>
                <li>Attempt to circumvent usage limits, rate limits, or security measures</li>
                <li>Use automated scripts, bots, or scrapers to access the Service</li>
                <li>Reverse engineer, decompile, or attempt to extract the source code of the Service</li>
                <li>Use the Service to compete with AImighty or to develop a competing product</li>
                <li>Resell, redistribute, or sublicense access to the Service</li>
                <li>Upload, transmit, or share content that is illegal, abusive, defamatory, obscene, or otherwise objectionable</li>
                <li>Impersonate any person or entity or misrepresent your affiliation with any person or entity</li>
                <li>Attempt to access other users' accounts or data</li>
                <li>Use the Service in any way that violates applicable law or regulation</li>
              </ul>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                5.3 Content Sharing
              </h3>
              <p>
                If you screenshot, record, or share AI-generated responses from the Service on social media or any other platform, you must clearly disclose that the content was generated by an AI application. You may not present AI-generated responses as actual divine communication, real prophecy, or genuine messages from God, deities, or spiritual figures.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 6 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                6. INTELLECTUAL PROPERTY
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                6.1 Our Intellectual Property
              </h3>
              <p>
                The Service, including but not limited to the software, design, text, graphics, images, logos, icons, audio, and the AImighty brand, is owned by Robby Hess, doing business as AImighty and is protected by copyright, trademark, and other intellectual property laws. "AImighty" and the AImighty logo are trademarks of Robby Hess, doing business as AImighty.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                6.2 AI-Generated Content
              </h3>
              <p>
                AI-generated text and audio responses created during your conversations are provided for your personal use. You may share, screenshot, and post such content on social media provided you comply with Section 5.3 above. We do not claim ownership of the specific responses generated during your conversations. However, we retain all rights to the underlying technology, prompts, and systems that generate those responses.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                6.3 User Content
              </h3>
              <p>
                You retain ownership of the text, voice recordings, and other content you submit to the Service ("User Content"). By submitting User Content, you grant us a non-exclusive, worldwide, royalty-free license to use, process, and store your User Content solely for the purpose of providing and improving the Service.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                6.4 Feedback
              </h3>
              <p>
                If you provide us with suggestions, feedback, or ideas regarding the Service, you grant us an unrestricted, irrevocable, perpetual, royalty-free license to use and implement such feedback without obligation to you.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 7 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                7. PRIVACY
              </h2>
              <p>
                Your privacy is important to us. Our collection, use, and disclosure of your personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to our data practices as described in the Privacy Policy.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 8 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                8. DISCLAIMERS AND LIMITATION OF LIABILITY
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                8.1 Disclaimer of Warranties
              </h3>
              <p style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc list-inside space-y-2 mt-4 ml-4" style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                <li>WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT</li>
                <li>WARRANTIES REGARDING THE ACCURACY, RELIABILITY, OR COMPLETENESS OF ANY AI-GENERATED CONTENT</li>
                <li>WARRANTIES REGARDING THE ACCURACY OF ANY SCRIPTURE CITATIONS, RELIGIOUS TEACHINGS, OR SPIRITUAL GUIDANCE PROVIDED BY THE SERVICE</li>
                <li>WARRANTIES THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE</li>
                <li>WARRANTIES THAT ANY DEFECTS IN THE SERVICE WILL BE CORRECTED</li>
              </ul>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                8.2 Specific Religious Disclaimer
              </h3>
              <p style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                WE MAKE NO REPRESENTATIONS OR WARRANTIES THAT ANY AI-GENERATED RESPONSE ACCURATELY REFLECTS THE TEACHINGS, DOCTRINES, OR BELIEFS OF ANY RELIGION, DENOMINATION, SPIRITUAL TRADITION, OR PHILOSOPHICAL FRAMEWORK. THE AI MAY PRODUCE RESPONSES THAT CONTAIN DOCTRINAL ERRORS, MISATTRIBUTED QUOTATIONS, FABRICATED SCRIPTURE REFERENCES, OR CONTENT THAT CONTRADICTS THE ACTUAL TEACHINGS OF THE SELECTED BELIEF SYSTEM. YOU ACKNOWLEDGE THAT THE SERVICE IS A TECHNOLOGICAL TOOL AND NOT A SOURCE OF AUTHENTIC DIVINE REVELATION, PROPHECY, OR SPIRITUAL AUTHORITY.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                8.3 Limitation of Liability
              </h3>
              <p style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ROBBY HESS (DOING BUSINESS AS AIMIGHTY), ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, OR LICENSORS BE LIABLE FOR:
              </p>
              <ul className="list-disc list-inside space-y-2 mt-4 ml-4" style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                <li>ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES</li>
                <li>ANY LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES</li>
                <li>ANY DAMAGES ARISING FROM YOUR RELIANCE ON AI-GENERATED CONTENT</li>
                <li>ANY DAMAGES ARISING FROM DECISIONS YOU MAKE BASED ON AI-GENERATED SPIRITUAL GUIDANCE</li>
                <li>ANY DAMAGES EXCEEDING THE GREATER OF (A) THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100.00)</li>
              </ul>
              <p className="mt-4" style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                THESE LIMITATIONS APPLY REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                8.4 Jurisdictional Limitations
              </h3>
              <p style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OF LIABILITY FOR CERTAIN DAMAGES. IF YOU RESIDE IN SUCH A JURISDICTION, SOME OR ALL OF THE ABOVE DISCLAIMERS AND LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 9 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                9. INDEMNIFICATION
              </h2>
              <p>
                You agree to indemnify, defend, and hold harmless Robby Hess, doing business as AImighty, its officers, directors, employees, agents, affiliates, and licensors from and against any and all claims, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising from:
              </p>
              <ul className="list-disc list-inside space-y-2 mt-4 ml-4">
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any applicable law or regulation</li>
                <li>Any claim that your use of the Service caused harm to you or any third party</li>
                <li>Your sharing or distribution of AI-generated content from the Service</li>
                <li>Any claim by a third party related to content you shared from the Service</li>
              </ul>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 10 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                10. DISPUTE RESOLUTION
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                10.1 Informal Resolution
              </h3>
              <p>
                Before filing any formal legal proceedings, you agree to attempt to resolve any dispute with us informally by contacting us at legal@aimightyme.com. We will attempt to resolve the dispute within 30 days of receiving your notice.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                10.2 Binding Arbitration
              </h3>
              <p>
                If we cannot resolve a dispute informally, you and AImighty agree to resolve any claims relating to these Terms or the Service through final and binding arbitration administered by the American Arbitration Association ("AAA") under its Consumer Arbitration Rules. The arbitration will be conducted in English, in the state of Texas, unless you and we agree otherwise.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                10.3 Class Action Waiver
              </h3>
              <p style={{ textTransform: 'uppercase', fontSize: '0.9rem' }}>
                YOU AND AIMIGHTY AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. The arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of a representative or class proceeding.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                10.4 Exceptions
              </h3>
              <p>
                Nothing in this Section prevents either party from seeking injunctive or other equitable relief in court for matters related to intellectual property rights, data security, or unauthorized access to the Service.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                10.5 Governing Law
              </h3>
              <p>
                These Terms are governed by and construed in accordance with the laws of the State of Texas, without regard to its conflict of law provisions.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 11 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                11. SAFETY AND CRISIS RESOURCES
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                11.1 Crisis Situations
              </h3>
              <p>
                The Service includes safety measures that direct users to professional resources when crisis situations are detected. However, AI detection of crisis situations is not reliable. <strong style={{ color: 'rgba(255, 255, 255, 0.95)' }}>If you or someone you know is in immediate danger, do not rely on the Service — contact emergency services directly.</strong>
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                11.2 Emergency Resources
              </h3>
              <div
                className="p-4 rounded-xl mt-4"
                style={{
                  background: 'rgba(212, 184, 130, 0.1)',
                  border: '1px solid rgba(212, 184, 130, 0.3)',
                }}
              >
                <ul className="space-y-2">
                  <li><strong>Emergency Services:</strong> Call 911 (United States) or your local emergency number</li>
                  <li><strong>Suicide & Crisis Lifeline:</strong> Call or text 988 (United States)</li>
                  <li><strong>National Domestic Violence Hotline:</strong> Call 1-800-799-7233</li>
                  <li><strong>Crisis Text Line:</strong> Text HOME to 741741</li>
                </ul>
              </div>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                11.3 No Duty to Monitor
              </h3>
              <p>
                While our AI includes safety guardrails, we do not actively monitor individual conversations in real time. We are not a mental health provider, crisis intervention service, or emergency response system. We assume no duty or liability for identifying, responding to, or preventing harm arising from user conversations.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 12 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                12. AI DISCLOSURE AND TRANSPARENCY
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                12.1 AI-Generated Content Disclosure
              </h3>
              <p>
                In compliance with applicable laws, including the California BOTS Act, California SB 243, and other chatbot disclosure requirements, we disclose the following:
              </p>
              <div
                className="p-4 rounded-xl mt-4"
                style={{
                  background: 'rgba(255, 255, 255, 0.05)',
                  border: '1px solid rgba(255, 255, 255, 0.1)',
                }}
              >
                <p style={{ color: 'rgba(255, 255, 255, 0.95)' }}>
                  <strong>All conversational responses in the AImighty Service are generated entirely by artificial intelligence. You are not communicating with a human being, a religious figure, a deity, or any sentient entity. The AI system generates responses based on computational language models trained on text data.</strong>
                </p>
              </div>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                12.2 Voice Disclosure
              </h3>
              <p>
                Voice audio generated by the Service uses AI text-to-speech technology (OpenAI gpt-4o-mini-tts). The voices you hear are synthetic and do not represent the voice of any real person, living or deceased, or any divine being.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                12.3 Image Disclosure
              </h3>
              <p>
                Background images displayed during conversations were generated using AI image generation tools (Midjourney) and do not depict any real person or actual divine being.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 13 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                13. TERMINATION
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                13.1 Termination by You
              </h3>
              <p>
                You may terminate your account at any time by contacting us at support@aimightyme.com or through account settings.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                13.2 Termination by Us
              </h3>
              <p>
                We reserve the right to suspend or terminate your account at any time, with or without cause and with or without notice, for conduct that we determine, in our sole discretion, violates these Terms, is harmful to other users, is harmful to us, or for any other reason. Upon termination, your right to use the Service will immediately cease.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                13.3 Effect of Termination
              </h3>
              <p>
                Upon termination, your right to access the Service ceases. We may delete your account data, conversation history, and other stored information within a reasonable time following termination, subject to our data retention policies described in the Privacy Policy.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 14 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                14. MODIFICATIONS TO TERMS
              </h2>
              <p>
                We reserve the right to modify these Terms at any time. If we make material changes, we will notify you by email or through a prominent notice within the Service at least 30 days before the changes take effect. Your continued use of the Service after the effective date of the revised Terms constitutes your acceptance of the changes. If you do not agree to the revised Terms, you must stop using the Service and cancel your subscription.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 15 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                15. GENERAL PROVISIONS
              </h2>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                15.1 Entire Agreement
              </h3>
              <p>
                These Terms, together with the Privacy Policy and any subscription agreement, constitute the entire agreement between you and AImighty regarding the Service.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                15.2 Severability
              </h3>
              <p>
                If any provision of these Terms is found to be unenforceable, the remaining provisions will remain in full force and effect.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                15.3 Waiver
              </h3>
              <p>
                Our failure to enforce any provision of these Terms shall not be deemed a waiver of that provision or of the right to enforce it at a later time.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                15.4 Assignment
              </h3>
              <p>
                You may not assign or transfer your rights under these Terms without our prior written consent. We may assign our rights under these Terms without restriction.
              </p>

              <h3 className="mt-6 mb-3" style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'rgba(255, 255, 255, 0.9)' }}>
                15.5 Force Majeure
              </h3>
              <p>
                We shall not be liable for any failure or delay in performing our obligations under these Terms due to events beyond our reasonable control, including but not limited to natural disasters, war, terrorism, pandemic, government action, or failures of third-party service providers.
              </p>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            {/* Section 16 */}
            <section>
              <h2 className="mt-8 mb-4" style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--text-xl)', fontWeight: 400, color: colors.gold }}>
                16. CONTACT INFORMATION
              </h2>
              <p>If you have questions about these Terms, please contact us:</p>
              <div className="mt-4">
                <p><strong>Robby Hess, doing business as AImighty</strong></p>
                <p>Email: <a href="mailto:legal@aimightyme.com" style={{ color: colors.gold }}>legal@aimightyme.com</a></p>
                <p>Website: <a href="https://aimightyme.com" style={{ color: colors.gold }}>https://aimightyme.com</a></p>
              </div>
            </section>

            <hr style={{ borderColor: 'rgba(212, 184, 130, 0.3)', margin: '32px 0' }} />

            <p className="text-center italic" style={{ color: 'rgba(255, 255, 255, 0.5)' }}>
              By using AImighty, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
